###########################################
# LobbySystem
# Created by BungeeDev aka MrCookieWarrior
# Development begin on 01.04.17
###########################################
Lobby:
    Prefix: "&8[&eLobby&aSystem&8] &f"
    AllowJoinMessage: true
    AllowQuitMessage: true
Messages:
    JoinMessage: "&e%player% &ahat den Server betreten!"
    QuitMessage: "&c%player% &4hat den Server verlassen!"