##############################################################
# LobbySystem
# Created by BungeeDev aka MrCookieWarrior
# Development begin on 01.04.17
##############################################################
Lobby:
    Prefix: "&8[&eLobby&aSystem&8] &f"
    AllowJoinMessage: true
    AllowQuitMessage: true
    AllowFood: false
    AllowWeatherChange: false
    AllowMobSpawming: false
    AllowPremiumChat: true
    MaxPlayer: 15
    AllowServerChat: true
    BungeeCord: true
    ServerName: "&3YouServer.net"
    Forum: "&6YourServer.net"
    TeamSpeak: "&2YourServer.net"
    LevelName: "world"
##############################################################
Messages:
    JoinMessage: "&e%player% &aJoined the game!"
    QuitMessage: "&c%player% &4Left the game!"
    NoPermCommand: "&cI´m sorry, but you do not have permission to perform this command!"
    NoPermBuild: "&cYou can't build here"
##############################################################
Title:
    Header: "&3Hello this plugin is OpenSource!"
    Footer: "&cYou must have Pex on your server"
##############################################################
Tablist:
    Header: "&2Welcome to my server: &eCeriox.de"
    Footer: "&7Our Forum: &ewww.ceriox.de\n&7Our TeamSpeak &eceriox.de"
##############################################################
MOTD:
    Header: ""
    Footer: ""
##############################################################