###########################################
# LobbySystem
# Created by BungeeDev aka MrCookieWarrior
# Development begin on 01.04.17
###########################################
Lobby:
    Prefix: "&8[&eLobby&aSystem&8] &f"
    AllowJoinMessage: true
    AllowQuitMessage: true
    AllowFood: false
    AllowWeatherChange: false
    AllowMobSpawming: false
    AllowPremiumChat: true
    MaxPlayer: 15
    AllowServerChat: true
##############################################################
Messages:
    JoinMessage: "&e%player% &ajoined the game!"
    QuitMessage: "&c%player% &4left the game!"
    NoPermCommand: "&ci´m sorry, but ypu do not have permission to perform this command!"
    NoPermBuild: "&cYou can't build here"
##############################################################
Title:
    Header: ""
    Footer: ""
##############################################################
Tablist:
    Header: ""
    Footer: ""
##############################################################
MOTD:
    Header: ""
    Footer: ""
##############################################################