name: Lobby
author: MrCookieWarrior
version: 1.0
main: de.mrcookiewarrior.lobby.main.Main
commands:
    warp:
        description:
    ban:
        description:
    check:
        description:
    unban:
        descrption:
    unmute:
        description:
    mute:
        descrption:
    kick:
        description: